name: Release and push docker image

on:
  push:
    branches:
      - "main"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build-and-test
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: decentraland/gh-action-release@0.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: get latest release and export as GIT_TAG
        id: release-tag
        run: echo "GIT_TAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1)" >> $GITHUB_ENV
    outputs:
      release-version: ${{ env.GIT_TAG }}

  push:
    needs: release
    if: ${{ success() }}
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: lamb2
      docker-tag: ${{ needs.release.outputs.release-version }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
